import "./globals.css";

export const metadata = {
  title: "AETHER™",
  description: "Generated by create next app",
  icons: [
    {
      url: "/AetherIcon.ico",
      media: "(prefers-color-scheme: light)",
    },
    {
      url: "/AetherIcon-dark.ico",
      media: "(prefers-color-scheme: dark)",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
